spring:
  datasource:
    url: jdbc\:mysql\://1.14.73.37\:3306/dynamicdatasource?useUnicode\=true&characterEncoding\=UTF-8&zeroDateTimeBehavior\=convertToNull&useSSL\=false&allowMultiQueries\=true&serverTimezone=Asia/Shanghai
    username: dmds
    password: qwer1234.
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      # 初始化连接池大小
      initial-size: 0
      # 连接池最大使用连接数量
      max-active: 20
      # 连接池最小空闲
      min-idle: 0
      # 获取连接最大等待时间
      max-wait: 6000
      validation-query: SELECT 1
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 25200000
      # 打开removeAbandoned功能,多少时间内必须关闭连接
      removeAbandoned: true
      # 1800秒，也就是30分钟
      remove-abandoned-timeout: 1800
      log-abandoned: true
      filters: mergeStat
mybatis:
  type-handlers-package: com.monochrome.dynamicdatasource.typehandler
  configuration:
    map-underscore-to-camel-case: true